version: '3'

services:

  web:
    build:
      context: my_php_project
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: my_php_project
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  nginx:
    container_name: new.nginx
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - .:Desktop/my_php_project
      - ./apps/common/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/common/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    extra_hosts:
      - "storage.app:127.0.0.1"
    ports:
      - "80:80"
      - "443:443"
